### ISSUE TITLE
Remove dist from npmignore

### ISSUE THREAD

**Issue by singhamrinder** [joshbtn/excelFormulaUtilitiesJS#32]
I am currently working on an Angular 2 app which uses npm as its dependency package manager. Seems like dist is there in npmignore, So not able to use the library directly on my web app without a build step.

**Comment by joshbtn** [comment]
This is some good feedback thanks!  I'll make this change later today.  I've been meaning to create a [bower](http://bower.io/) package as well.

**Comment by joshbtn** [comment]
@singhamrinder, I've made this change and published it to npm.  Let me know if it works for you.

**Comment by singhamrinder** [comment]
@joshbtn Thanks, worked for me.
