### ISSUE TITLE
Wrong order in concatenated dist file.

### ISSUE THREAD

**Issue by singhamrinder** [joshbtn/excelFormulaUtilitiesJS#33]
Hi, I have include dist folder in my project and tried to use the concatenated file. But it seems like core.js file is appended after ExcelFormulaUtils.js. Because of that when i include dist/excel-formula.js.
it gives error 
Uncaught TypeError: Cannot read property 'formatStr' of undefined
(anonymous function) @ excel-formula.js:19
(anonymous function) @ excel-formula.js:1191

Seems like a build step issue.

**Comment by joshbtn** [comment]
Thanks again @singhamrinder , got a fix coming up shortly.

**Comment by joshbtn** [comment]
the npm, package has been update.
