### ISSUE TITLE
How to convert to js calculation function

### ISSUE THREAD

**Issue by arammarm** [joshbtn/excelFormulaUtilitiesJS#36]
I did try example code. excelFormulaUtilities.formula2Javascript( "" ); got from basic_example1/index.html. But it's didn't working for me. it's said "Uncaught TypeError: excelFormulaUtilities.formula2Javascript is not a function" What can i do?

**Comment by joshbtn** [comment]
Sorry for that.  I've updated the basic example.  It was out of date and pointing to the wrong JS file.  See if that clears things up for you.

**Comment by arammarm** [comment]
what the F
