### ISSUE TITLE
Need real js calculation, not the result

### ISSUE THREAD

**Issue by oakmedia** [joshbtn/excelFormulaUtilitiesJS#37]
Hello,

i tried your class, but is it right, that it only calculates results. I can not see any line of Javacript Code. Could you perhaps help me?

Thanks,
Regards,
Olaf

**Comment by joshbtn** [comment]
I'm not sure I understand. Do you have an example or screenshot of how you are trying to use it?

**Comment by joshbtn** [comment]
Sorry, After reading this again I think I understand what you are asking.  This library only deals with converting formulas to the equivalent JavaScript. It will not 'solve' or resolve the resulting values of the JavaScript formulas.  

To get the results from the JavaScript formulas you will need to run the converted JavaScript paired with something like https://github.com/sutoiku/formula.js/ to make sure that all of the excel functions can be executed.

Hopefully this answers your question?

**Comment by oakmedia** [comment]
Hi Josh,

yes i think this will help a little bit... thank you.

Regards,

Olaf

Am 12.05.2016 um 17:54 schrieb Josh Bennett:
