### ISSUE TITLE
Not giving the accurate functions (absolute, minimum & maximum)

### ISSUE THREAD

**Issue by kirti-kathpal** [joshbtn/excelFormulaUtilitiesJS#39]
I am using excelFormulaUtilities.formula2JavaScript('=min(2,3)') which gives me Math.Min(2,3)
But there's no function by this name. It should give me Math.min and not Math.Min.
Same is for the MIN & ABS.

**Comment by joshbtn** [comment]
Try including this library https://github.com/sutoiku/formula.js. They have done a nice job of porting all Excel functions to JS.

**Comment by singhamrinder** [comment]
The problem is the Upper case of the returned function.

For example input is min(1 ,2) for **formulaToJavascript** method it will give output as Math.Min(1, 2)
It should be Math.min(1, 2).

**Comment by joshbtn** [comment]
Sorry I misunderstood.  This should be an easy fix, I'll get this in shortly.

**Comment by joshbtn** [comment]
I made this change and updated the npm package. Thanks for your feedback.
