### ISSUE TITLE
I dont think that the excel to Java page is working?

### ISSUE THREAD

**Issue by branein** [joshbtn/excelFormulaUtilitiesJS#42]

**Comment by joshbtn** [comment]
It may be that there is something about your formula that it doesn't handle.  Unfortunately it don't have any formula error checking or warnings, it just fails silently.  If you try to convert the example it should work.  If you are still having trouble please provide the browser you are using.  If your formula doesn't contain any sensitive data feel free to post it here so I can take a look.
