### ISSUE TITLE
formula to javascript converts max to Math.Max

### ISSUE THREAD

**Issue by totalsky** [joshbtn/excelFormulaUtilitiesJS#44]
`=MAX(A1,A2)` is converted to `Math.Max(A1,A2)`.  Shouldn't it be `Math.max(A1,A2)`?

**Comment by joshbtn** [comment]
Hi totalsky,

You are right, thanks for the feedback.  I'll get a fix in with the next release.

**Comment by joshbtn** [comment]
This has been fixed.
