### ISSUE TITLE
Beautify Excel; make dropdown lists

### ISSUE THREAD

**Issue by Greedquest** [joshbtn/excelFormulaUtilitiesJS#48]
Love the Beautify excel tool, really nice and simple, thanks for designing it!

Just thought it would be cool if instead of having the function fully laid out, you could expand different parts of it to reveal deeper layers of the formula, just not all at once. Like a reddit post when you click the [+] to expand.

**Comment by joshbtn** [comment]
Thanks for the feedback Greedquest!  I like the idea. I'm thin on time these days but I'll bat around some implementation Ideas, maybe there's a straight forward way to do this.

**Comment by Greedquest** [comment]
Duplicate of #15
