### ISSUE TITLE
How to add something like ROUNDUP/ROUNDDOWN?

### ISSUE THREAD

**Issue by jimmack1963** [joshbtn/excelFormulaUtilitiesJS#49]
Hi,

I need to handle Roundup & down.  Is there any written reference of the places I'd need to hit?  Or, is there a current function/code checkin that I could base my changes on?

Thank you for this useful library!

**Comment by joshbtn** [comment]
Hi Jimmack1963,

Are you trying to convert a  formula containing roundup/rounddown to JavaScript and have it execute?  if so you should checkout https://github.com/sutoiku/formula.js/.  This library does a nice job of implementing many of the excel functions in JavaScript.

Thanks for the feedback!
