### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by ateichman** [joshbtn/excelFormulaUtilitiesJS#54]
A total brainsaver, this tool! Thanks.

I'd request the addition of a copy to clipboard button, for easy copying of the extended beautify output. Sometimes it's easier to print and scribble for working stuff out, and a copy button would facilitate quick transfer to a text editor.

**Comment by joshbtn** [comment]
Thanks for the feedback @ateichman!  Sounds like a good idea to me, I'll see about including this in my next release.

**Comment by joshbtn** [comment]
This feature has been added.
