### ISSUE TITLE
HTML tags cause glitches

### ISSUE THREAD

**Issue by BevansDesign** [joshbtn/excelFormulaUtilitiesJS#58]
If I have any HTML tags in my formulas (between quotation marks, naturally), they're displayed as if they're part of the page source code. So, if I have a formula that says:

`="<a href=#>test</a>`

It will show up like:

[test](#)

**Comment by joshbtn** [comment]
Hi @BevansDesign,

I'll have a fix for this in the next release, thanks for the feedback!

**Comment by joshbtn** [comment]
Hi @BevansDesign,

This fix is in.  Thanks again
