### ISSUE TITLE
[BUG] JS on the website doesn't seem to be working for internet explorer 11

### ISSUE THREAD

**Issue by akg518** [joshbtn/excelFormulaUtilitiesJS#60]
Hitting some JavaScript error, no output is being generated for any formulas I type.

Error message below:

SCRIPT438: Object doesn't support property or method 'parseInt'
File: beautifier.min.js, Line: 1, Column: 1488

**Comment by joshbtn** [comment]
Thanks for the feedback.  I'll have a fix for this in the next release.

**Comment by joshbtn** [comment]
I found the problem and pushed the fix.

**Comment by joshbtn** [comment]
Looks lie there's still an issue, re-opening.  Being a mac/linux user makes testing hard.
