### ISSUE TITLE
Support for https

### ISSUE THREAD

**Issue by glawrence** [joshbtn/excelFormulaUtilitiesJS#65]
Great work with http://excelformulabeautifier.com/ thanks for doing this. However, it would be nice to see an https version, even if that was on https://excelformulabeautifier.github.io/ or something

**Comment by 9mido** [comment]
Can we please have this become HTTPS? It would be nice to be able to share this link but the fact that is is HTTP and not secure makes people think that you are sending them malware.

**Comment by joshbtn** [comment]
Walked though these instructions https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https.  It seems to be working with https me now.  I ended up adding a www. to the mix, seemed to fix some warnings I was seeing, not 100% sure it was needed though.
