### ISSUE TITLE
formatFormula* with array literals has buggy output

### ISSUE THREAD

**Issue by brainysmurf** [joshbtn/excelFormulaUtilitiesJS#89]
For example, the simple legal formula:

```
={F2:G}
```

results in:

```
={ F2:G
  ARRAYROWSTOP)
ARRAYSTOP)
```

I'm happy to help figure out but could use some pointers on how to adjust the algorithm.

**Comment by joshbtn** [comment]
Fixed in https://github.com/joshbtn/excelFormulaUtilitiesJS/pull/92
